version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
